#pragma once

#define MAX_BUFFER 1300

#define MAX_PLAYERS 2
#define MIN_SQUARE 20
#define HEADER_HELLO "HELLO"
#define HEADER_WELCOME "WELCOME"
#define HEADER_FULL "FULL"
#define HEADER_TRYPOSITION "TRYPOSITION"
#define HEADER_POSITION "POSITION"
#define HEADER_EXIT "EXIT"